### ISSUE TITLE
Vitals does not use modifier_cd for position

### ISSUE THREAD

**Issue by jklann** [SCILHS/i2p-transform#12]
Vitals transform should pull position from modifier_cd, but is looking only at concept_cd

**Comment by jklann** [comment]
Fixed in MSSQL, but needs to be tested on some data.

**Comment by matthewjoss** [comment]
I added the oracle label even though this is yet to be tested on some data in MSSQL

**Comment by matthewjoss** [comment]
I tested this in MSSQL, and pmnVITAL appears to be acquiring the correct outputs for the modifier codes

**Comment by matthewjoss** [comment]
Fixed in Oracle Loader, tested with success.
