### ISSUE TITLE
*_TIME fields are using 12 hour clock not 24 hour clock

### ISSUE THREAD

**Issue by keithwanta** [SCILHS/i2p-transform#13]
The *_TIME fields in the CDM are built based on a 12 hour clock.  For example, a date with a time of 00:00:00 get converted to 12:00.  This might be a problem for encounters that result from dispensed medications.  I suppose BIRTH_TIME might be critical for certain metrics, if the time wasn't properly converted.

**Comment by dckc** [comment]
@ngraham @mprittie I wonder if our times got mangled because of this. I suppose the fix is to use HH24 instead of HH somewhere.

**Comment by matthewjoss** [comment]
Fixed in Oracle.

**Comment by dckc** [comment]
Where exactly was this fixed? Which revision?

**Comment by matthewjoss** [comment]
That was all in the 83c696a commit

**Comment by dckc** [comment]
Thanks.
