### ISSUE TITLE
Building the prescribing table in Oracle exhausts TEMP space

### ISSUE THREAD

**Issue by njgraham** [SCILHS/i2p-transform#20]
When we ran the `PCORNetPrescribing` procedure, Oracle reported the following error:

```
ERROR at line 1:
ORA-12801: error signaled in parallel query server P005
ORA-01652: unable to extend temp segment by 32 in tablespace TEMP
ORA-06512: at "PCORNET_CDM.PCORNETPRESCRIBING", line 53
ORA-06512: at "PCORNET_CDM.PCORNETLOADER", line 12
```

We had allocated 800 GB for temp space and Oracle used it all before failing.  We have 231,890,680 medication facts on 532,992 patients in our i2b2 fact table.

I'm curious if this is something that someone else has run in to?  Specifically, I'm curious about the Wake Forest team since I believe they made the Oracle port and presumably ran it against their i2b2 instance.

**Comment by jklann** [comment]
@ctsb at Wake Forest, have you seen anything like this? Or @mikemendis , since you've worked with a couple Oracle installs?

**Comment by aaronabend** [comment]
Duplicates can cause problems like this since they can generate large Cartesian products.  Just a wild guess though.

**Comment by jklann** [comment]
Matt applied Nathan's change to Oracle
