### ISSUE TITLE
RX_FREQUENCY:02 vs 02 in pcori_basecode

### ISSUE THREAD

**Issue by dckc** [SCILHS/i2p-transform#25]
Please see [Jun 16 discussion](https://github.com/kumc-bmi/i2p-transform/pull/35#discussion_r67436558).

_IOU a better bug report_

**Comment by matthewjoss** [comment]
I fixed the substring lines in the prescribing procedure. Was this all that needed changing?

**Comment by jklann** [comment]
Yes!
