### ISSUE TITLE
Synonyms for pmnxxx->xxx

### ISSUE THREAD

**Issue by jklann** [SCILHS/i2p-transform#27]
Script should create synonyms for the pmnxxx tables without the pmn prefix, for use by the Menu Driven Query tool. 

See the [SAS create table statements](https://github.com/SCILHS/i2p-transform/blob/master/SAS/CDM2sas_mssql.sas) for a list of correct table names.

Thanks @ctsb for pointing this out!

**Comment by matthewjoss** [comment]
Completed and synced with github for both versions of the loader
