### ISSUE TITLE
support DEATH table?

### ISSUE THREAD

**Issue by dckc** [SCILHS/i2p-transform#3]
I see no support for the death table. In particular, `insert into pmndeath` doesn't occur.

I suppose this isn't one of the 7 tables PCORnet is focussed on for [Phase II Diagnostic and Data Characterization Queries timeline](https://pcornet.imeetcentral.com/drnoc-workgroups/file/43823210/) but @rwaitman, @mprittie, @njgraham and I were discussing it today, so I'm opening this to stay tuned to thoughts from anyone else on the matter.

7 tables, i.e. DEMOGRAPHIC, ENROLLMENT, ENCOUNTER, DIAGNOSIS, PROCEDURES, VITAL, and HARVEST.

**Comment by jklann** [comment]
Yes, the death table isn't supported yet over here. I have an alpha version staged on a server somewhere, but there was an issue with date querying that I haven't had time to resolve. Happy to share the alpha version if you'd like to develop it further, maybe on our private repository.

**Comment by dckc** [comment]
Sharing it on a branch would be the conventional thing to do. That would be great.

**Comment by jklann** [comment]
Simple DEATH transform using patient_dimension data added in MSSQL.

**Comment by matthewjoss** [comment]
I translated Jeff's simple Death transform from MSSQL to the Oracle script.
