### ISSUE TITLE
all CONDITIONs have RESOLVE_DATE?

### ISSUE THREAD

**Issue by dckc** [SCILHS/i2p-transform#30]
The RESOLVE_DATE on the CONDITION table is computed as `NVL(max(factline.end_date),null) resolve_date`. We have `end_date` populated on all our facts (otherwise the timeline plugin goes kerflewey) so this results in CONDITIONs looking like they are resolved.

Is this by design? Or are we doing it wrong somehow?

cc @rwaitman, @ngraham

For reference, the [PCORNet CDM spec](http://www.pcornet.org/pcornet-common-data-model/) says:

> Date condition was resolved, if resolution of a transient condition has been achieved.

**Comment by jklann** [comment]
Just catching up on my issues.... how do you then indicate a condition is resolved?

We must not use our own timeline plugin because we have many null end dates :)

**Comment by dckc** [comment]
We reflect the Epic problem status (active, resolved, ...) in a modifier.

Sounds like maybe we should fix the timeline plugin to handle missing end-date.

**Comment by jklann** [comment]
Closing but will tell Dave Wang.
