### ISSUE TITLE
PCORNet diagnosis table replication errors

### ISSUE THREAD

**Issue by jklann** [SCILHS/i2p-transform#35]
In the PCORnet diagnosis transform, admit_date and provider_id should source its value from the encounter table, not factline

**Comment by matthewjoss** [comment]
Fixed in both transforms... although 'provider_id' needs to be tested properly on real data

**Comment by jklann** [comment]
Hmm, I don't think I intended the joins to reference the encounter table, just the select statement. I changed it back and am testing.

**Comment by jklann** [comment]
Oh, I only changed it back in MSSQL for testing.

**Comment by jklann** [comment]
I think the status is this needs to be tested in Oracle
