### ISSUE TITLE
only patients active since 2010?

### ISSUE THREAD

**Issue by dckc** [SCILHS/i2p-transform#4]
Why limit the CDM ETL to patients active since 2010?

@njgraham, I wonder if this constraint is applicable to us.

cc @mprittie, @rwaitman

``` sql
select DISTINCT PATIENT_NUM from I2B2FACT where START_DATE > to_date('01-Jan-2010','dd-mon-rrrr')
```

https://github.com/SCILHS/i2p-transform/blob/master/Oracle/PCORNetLoader_ora.sql#L70

**Comment by jklann** [comment]
Agreed that this is not necessarily applicable to GPC. SCILHS has decided to standardize the start date of 1-1-10. Note also that the loyalty cohort finder has hard-coded dates at the moment:

https://github.com/SCILHS/SCILHS-utils/blob/master/LoyaltyCohort/LoyaltyCohort-ora.sql#L225

**Comment by dckc** [comment]
Our approach to this is to parameterize `min_pat_list_date_dd_mon_rrrr`.

I'm trying to isolate it as its own pull request, but I'm not having much luck.

Meanwhile, see https://github.com/kumc-bmi/i2p-transform/commit/3eee53e9714058b4030858d829ce8b3aeee3573f

**Comment by dckc** [comment]
The 2010 timeframe from i2p-transform doesn't seem to apply to the DEMOGRAPHIC table. We have just as many pcornet DEMOGRAPHIC records as we have i2b2 patient_dimension records. Is that by design? Or did we goof somehow?

cc @njgraham @rwaitman @mprittie

p.s. I found rationale for the 2010 cut-off in some PCORnet requirements somewhere, so we are sticking to it as well. Here's hoping I manage to cite them sometime.

**Comment by jklann** [comment]
Hmm, search for "i2b2patient_list" in the transform. You shouldn't get all of the patient_dimension, just those with records since 1/1/2010.

**Comment by matthewjoss** [comment]
I added the oracle label, even though I think this also still exists in the MSSQL code

**Comment by jklann** [comment]
Demographic now pulls only patients since 1-1-2010. The parameterized run script allows changed date constraints in MSSQL; will implement in Oracle.
