### ISSUE TITLE
Lab RESULT_QUAL should be mapped to OT for this round

### ISSUE THREAD

**Issue by jklann** [SCILHS/i2p-transform#44]
Because we haven't standardized tval_char for lab results yet, all non-null tval_char should be mapped to null for the moment.

E.g., change this line
`CASE WHEN m.ValType_Cd='T' THEN isnull(substring(nullif(m.TVal_Char,''),1,12),'NI') ELSE 'NI' END RESULT_QUAL,`

to

`CASE WHEN m.ValType_Cd='T' THEN CASE WHEN m.Tval_Char IS NOT NULL THEN 'OT' ELSE 'NI' END END RESULT_QUAL,`

(though please test this)

**Comment by matthewjoss** [comment]
All set for both MSSQL and Oracle.
