### ISSUE TITLE
Update CDM version to 3.1 in Harvest table

### ISSUE THREAD

**Issue by jklann** [SCILHS/i2p-transform#59]
Dear Network Liaisons,

This email serves as a reminder to have all DataMart Administrators check and update all HARVEST table information before running the Data Curation Query package. This includes:

Updating the CDM version to 3.1
Making sure all other variables match the HARVEST reference table
Updating refresh dates
Ensuring all other information is up-to-date and accurate.
 
It is key to have accurate information in the HARVEST table because it captures DataMart attributes not stored elsewhere that are used extensively by the DRN OC and study teams. Therefore, we will not accept responses that have errors in the HARVEST table, as stated on page 17 of the Work Plan and in the DRN OC slidedeck that was circulated June 29th (both documents are attached).

Thanks,

The Data Curation Team

**Comment by matthewjoss** [comment]
done in MSSQL and Oracle
