### ISSUE TITLE
Missing LAB_NAME column in pmnLabResult_cm table 

### ISSUE THREAD

**Issue by galozins** [SCILHS/i2p-transform#64]
The latest PCORNetLoader (July 2018) does not create LAB_NAME column in the pmnlab_result_cm table but the PCORNetLabResult_cm stored procedure inserts data into the column. Executing the SP gives "invalid column" error.

**Comment by matthewjoss** [comment]
Thanks for this. I had fixed on my local copy and forgot to push. Just pushed it back up.
