### ISSUE TITLE
SPECIMEN_SOURCE is showing invalid value in DCQ

### ISSUE THREAD

**Issue by jklann** [SCILHS/i2p-transform#66]
SPECIMEN_SOURCE is showing invalid value in DCQ

NI appears to be legal and so it should be changed to this, but Galina might have done this on her data and it didn't work?

**Comment by galozins** [comment]
We had blank (not 'NI' or NULL) entries in the SPECIMEN_SOURCE column after the transform. This is most likely what has caused the error. I have changed the blank values to 'NI' but have not re-run the transform yet, wanted to fix all errors before the next run.

**Comment by jklann** [comment]
Ok, we need to update the transform to make NI the default value in specimen_source

**Comment by jklann** [comment]
Commit c346afa75cb64fad36050557a70bad93e00fe194 fixes this in MSSQL, though DCQ still needs to be rerun. The problem seems to be that sometimes the ontology is imported with a blank value in the specimen_source column when it should be null.

**Comment by jklann** [comment]
Matt fixed in Oracle 90090467b6d7460644af2e11486d9ed16cb48561
