### ISSUE TITLE
Numeric fields are varchar

### ISSUE THREAD

**Issue by jklann** [SCILHS/i2p-transform#68]
MEDADMIN_START_TIME
MEDADMIN_STOP_TIME
OBSCLIN_TIME
OBSGEN_TIME

are all numeric and should be varchar

**Comment by galozins** [comment]
The fields are varchar(5) in PopMedNet and Pcornet CDM 4.0 specs list the columns as TEXT(5) but the EDC report seems to expect them as numeric.

**Comment by jklann** [comment]
The spec requires different data types in SQL and SAS, for some reason. Commit 42692cb71c858db6a3572d08e3ac7c0e545a093d fixes this in the SAS script.
