### ISSUE TITLE
Referencing missing columns in PCORNetEncounter procedure

### ISSUE THREAD

**Issue by keithwanta** [SCILHS/i2p-transform#7]
Take a look at my pull request.  

Pull request was under "University of Wisconsin-HIMC" organization.
See file i2p-transform/Oracle/PCORNetLoader_ora.sql

You'll notice where the PCORNetEncounter procedure is being created, I placed 6 TODO comments with missing columns.  There was either code missing that wasn't committed to the i2p-transform, or I must have skipped over some code that I shouldn't have.  I see these 6 columns are documented in the CDM v3 guide.

**Comment by jklann** [comment]
I suppose I might have missed including DDL to add the 6 columns to the visit_dimension. If you've done this, can you submit a pull request in the ontology repo? And then close this issue? Thanks.

**Comment by keithwanta** [comment]
Jeff, since there's been so many updates to this code since March, I'm going to rebase my fork and add the Netezza code to the new pull request.  I'll do my best to re-review the Oracle code.

For reference, these are the 6 columns from PcornetEncounter:  providerid, location_zip, facility_id, discharge_disposition, discharge_status and admitting_source.

```
select 
  distinct v.patient_num, 
  v.encounter_num,  
  start_Date, 
  to_char(start_Date,'HH:MI'), 
  end_Date, 
  to_char(end_Date,'HH:MI'), 
  '', -- providerid, -- <------------------------------------------------------------------- TODO
  '', -- location_zip -- <------------------------------------------------------------------ TODO
  (case when pcori_enctype is not null then pcori_enctype else 'UN' end) enc_type,
  '', -- facility_id, -- <------------------------------------------------------------------ TODO
  'NI', -- CASE WHEN pcori_enctype='AV' THEN 'NI' ELSE discharge_disposition END,  -- <----- TODO
  'NI', -- CASE WHEN pcori_enctype='AV' THEN 'NI' ELSE discharge_status END,  -- <---------- TODO
  drg.drg, 
  drg_type, 
  'NI' -- CASE WHEN admitting_source IS NULL THEN 'NI' ELSE admitting_source END -- <------- TODO

```

**Comment by jklann** [comment]
I think this is done
