### ISSUE TITLE
pcornet_parsecode fails on NULL value in  "codestring" parameter

### ISSUE THREAD

**Issue by keithwanta** [SCILHS/i2p-transform#8]
The procedure pcornet_parsecode in PCORNETLoader_ora.sql (Oracle script) should either check for a NULL value in the codestring parameter.  Or the code (or procedure) that calls it should check for an argument value of NULL for the codestring parameter.

There's a conflict of interest here.  PCORNET_DEMO doesn't allow NULL values in C_DIMCODE, yet the ontology has NULL values in C_DIMCODE.  

Do I trust the data (in the i2p-ontology repo) or the Oracle source code?  Looks like the source code matches the DDL, so that's good.  This question also applies to the other ontologies with NULL values in this field.

**Comment by jklann** [comment]
Looking at the code, it appears that strings are skipped if it is not a quoted, comma-separated list. And the null issue in the dimcode is fixed now over in the ontology repo. If this is resolved, can you close it? Thanks.

**Comment by keithwanta** [comment]
Resolved.  Closing for now.
